### ISSUE TITLE
Missing explcicit license

### ISSUE THREAD

**Issue by Geolykt** [Unprotesting/Auto-Tune#7]
There is currently no explicit license, which especially on Github can be problematic and even more so thanks to bukkit's license which makes matters even more complicated, I recommend you to set the license explicitly as otherwise potential contributors may not know what they can do with the application and source. It also becomes a legal pain as the bukkit-api is licensed under the GPL which technically forces any Deriviates to be GPL (not a lawyer speaking though) which means the implied all rights reserved points back to GPL, which according to #6 you may not want to perform (GPL forces a work to be open sourced).

**Comment by Unprotesting** [comment]
Thank you do taking the time to contribute and consider the project. Can I ask why not having a license is such a problem. Also what license do you recommend? I want people to be able to make changes to auto tune the plugin but not to have access to the price setting API which is why that is seperate and not open source.

**Comment by Geolykt** [comment]
Well, the backend itself has to be licensed under GPL if the common consensus of the spigotmc and other community is to be heard (that plugins are a derivative of the bukkit api by extending JavaPlugin in the main class). The backend in itself can be any license you want however since that is put behind a network and is not communicating any complex datatypes and as such can be freely closed source.
The price setting API (on the client) cannot be protected from being altered though under most licenses (even under licenses like MIT, BSD, AGPL, WTFPL, LGPL, Beerwave and other similar licenses)

In the end the implied GPL license is not a real problem, can lead to confusion over time however. It is thus recommended to not pick the default "all rights reserved" stance on code sharing plattforms that also alter the rights of the author (such as Github allows forks iirc)

As always, I'm not a lawyer

**Comment by Unprotesting** [comment]
There isn't an price setting API within the client so I don't need to worry about people taking the price setting section of the plugin as it's all backend. I'll add the GPL license to the plugin when I next push a commit wich will be in a couple hours when I get home. Thank you for bringing this up though its good to understand exactly what needs to be done when creating a plugin sorrounding legal stuff so I will be taking your advice and adding a license as quick as possible. It would also be good to have some other people working on the project because it's been 99% me the past 6 months and this will allow people to do that.

**Comment by Unprotesting** [comment]
OK I have added the GNU GPL v3 to the project. Please let me know if there are any other issues.

**Comment by Geolykt** [comment]
Ok
